wd: wd_cipher: remove warning on sched_getcpu
wd_cipher.c:173:8: warning: implicit declaration of function ‘sched_getcpu’; did you mean ‘sched_getparam’? [-Wimplicit-function-declaration]
  cpu = sched_getcpu();
        ^~~~~~~~~~~~
        sched_getparam

According to the comments on sched_getcpu(), the feature macro is missed.

       int sched_getcpu(void);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       sched_getcpu():
           Since glibc 2.14:
               _GNU_SOURCE
           Before glibc 2.14:
               _BSD_SOURCE || _SVID_SOURCE
                   /* _GNU_SOURCE also suffices */

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>