uadk: fix the compilation failure of wd_alg.h
Fix the compilation failure of wd_alg.h, error log likes:
wd_alg.h:121:9: error: unknown type name ‘__u8’.
And improve code portability by including linux/types.h
instead of asm/types.h.

Signed-off-by: Weili Qian <qianweili@huawei.com>