wd: add missing header file wd_ecc.h
Fix openssl-uadk build error.
uadk_ecc.c:8:25: fatal error: uadk/wd_ecc.h: No such file or directory

Signed-off-by: Zhangfei Gao <zhangfei.gao@linaro.org>