wd: add missing header file in make install
wd_common.h is not copied to include when make install
As a result, openssl-uadk is build error.
/usr/local/include/uadk/wd_alg_common.h:7:23: fatal error: wd_common.h: No such file or directory

Signed-off-by: Zhangfei Gao <zhangfei.gao@linaro.org>