wd: v1: append missing libcrypto in hpre test
/usr/bin/ld: test_hisi_hpre.o: in function `hpre_test_result_check':
/home/hzhuang1/uadk/v1/test/hisi_hpre_test/test_hisi_hpre.c:7171: undefined reference to `RSA_new'
/usr/bin/ld: test_hisi_hpre.o: in function `hpre_bin_to_bn':
/home/hzhuang1/uadk/v1/test/hisi_hpre_test/test_hisi_hpre.c:7157: undefined reference to `BN_bin2bn'

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>