wd: force to embed wd_crypto objects in vendor lib
Since test app needs to link libwd_crypto and libhisi_hpre in static
mode, and libhisi_hpre needs to invoke APIs in libwd_crypto.

Force wd_crypto objects could be embedded in libhisi_hpre.a.

/bin/bash ../../libtool  --tag=CC   --mode=link aarch64-linux-gnu-gcc -Wall -fno-strict-aliasing -I../../include -pthread -g -O2 -Wl,-rpath,'/usr/local/lib'  -o test_hisi_hpre test_hisi_hpre.o ../../.libs/libwd.a ../../.libs/libwd_crypto.a ../../.libs/libhisi_hpre.a
libtool: link: aarch64-linux-gnu-gcc -Wall -fno-strict-aliasing -I../../include -pthread -g -O2 -Wl,-rpath -Wl,/usr/local/lib -o test_hisi_hpre test_hisi_hpre.o  ../../.libs/libwd.a ../../.libs/libwd_crypto.a ../../.libs/libhisi_hpre.a -pthread
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_sign_out_transfer':
/home/hzhuang1/uadk/drv/hisi_hpre.c:1225: undefined reference to `wd_sm2_get_sign_out_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `sm2_enc_out_transfer':
/home/hzhuang1/uadk/drv/hisi_hpre.c:1279: undefined reference to `wd_sm2_get_enc_out_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `sm2_kg_out_transfer':
/home/hzhuang1/uadk/drv/hisi_hpre.c:1259: undefined reference to `wd_sm2_get_kg_out_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_prepare_pubkey':
/home/hzhuang1/uadk/drv/hisi_hpre.c:847: undefined reference to `wd_ecc_get_pubkey_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_prepare_prikey':
/home/hzhuang1/uadk/drv/hisi_hpre.c:784: undefined reference to `wd_ecc_get_prikey_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_prepare_sign_in':
/home/hzhuang1/uadk/drv/hisi_hpre.c:970: undefined reference to `wd_ecc_get_prikey_params'
collect2: error: ld returned 1 exit status

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>